#!/usr/bin/env bash
# custom header

sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello world" Welcome to my server > /var/www/html/index.html


echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
# Configuring redirection
sudo sed -i '/^\sserver_name.*/a \        rewrite ^/redirect_me https://www.kemten.tech  permanent;' /etc/nginx/sites-available/default
# Custom error page
sudo sed -i '/^\slocation.*/i \        error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
# Configuring response header
sudo sed -i '/^\slocation.*/i \        add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
